---     QUESTION NO 1
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;
---     QUESTION NO 2
SELECT SUM(TOTAL_PRICE) / COUNT(DISTINCT ORDER_ID) AS AVERAGE_ORDER_VALUE FROM PIZZA_SALES;
---     QUESTION NO 3
SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SELL FROM PIZZA_SALES;
---     QUESTION NO 4
SELECT COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;
---      QUESTION 5
SELECT CAST(SUM(QUANTITY) AS DECIMAL(10,2))/ COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;



SELECT * FROM PIZZA_SALES;



---   QUESTIONS 2.1 --- DAILY TREND FOR TOTAL ORDERS

SELECT TO_CHAR(ORDER_DATE, 'DAY') AS ORDER_DAY,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE, 'DAY')
ORDER BY MIN(ORDER_DATE);


---  QUESTION 2.2  --- HOURLY TREND FOR TOTAL ORDERS

SELECT  EXTRACT (HOUR FROM ORDER_TIME) AS ORDER_HOUR,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY EXTRACT (HOUR FROM ORDER_TIME)
ORDER BY ORDER_HOUR;

---  QUESTION 2.3  --- PERCENTAGE OF SALES BY PIZZA CATEGORY

SELECT 
    pizza_category, 
    (SUM(total_price) * 100.0) / (SELECT SUM(total_price) FROM pizza_sales) AS sales_percentage
FROM 
    pizza_sales
GROUP BY 
    pizza_category;

